name: Test-01

# Run this workflow every time a new commit pushed to your repository
# on: push
on: 
  schedule:
    - cron: '*/5 * * * *'

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  commit-result-01:
    # Name the Job
    name: Test commit result - 01
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # You can make whatever type of change to the repo...
      # - run: echo "123" > ./file.txt
      - run: curl "https://s.weibo.com/ajax/jsonp/gettopsug" >> ./sina.txt 
      - run: echo '\n' >> ./sina.txt

      # ...and then use the action as you would normally do, but providing the path to the repo
      - uses: EndBug/add-and-commit@v6
        with:
          message: 'Add the very useful text file'
          add: '*.txt --force'
      #    cwd: './pathToRepo/'
